# Generated by Django 4.2.10 on 2024-04-26 19:41

import GameCollectionAPI.models.game
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GameCollectionAPI', '0003_rating_delete_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(default=GameCollectionAPI.models.game.get_default_user_id, on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
    ]
