# Generated by Django 4.2.10 on 2024-04-30 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameCollectionAPI', '0007_game_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='platforms',
            new_name='platform_id',
        ),
    ]
