# Generated by Django 4.2.10 on 2024-05-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameCollectionAPI', '0009_remove_game_platform_id_game_platforms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='length',
        ),
    ]
